src/DataManagementSystem/Uni/urls.py
from django.contrib import admin
from django.views.generic.base import RedirectView
from django.urls import path, include, re_path
from mainapp import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('', views.user_login, name="login"),
    path('update/', include('updateapp.urls')),
    path('admin/', admin.site.urls),
    path('home_page/', views.home_page, name="home_page"),
    path('logout/', views.user_logout, name="logout"),
    path('my_space', views.my_space, name="my_space"),
    path('results_page/<str:my_query>/', views.results_page, name="results_page"),
    path('search_page/', views.search_page, name="search_page"),
    path('sign_up/', views.sign_up_page, name="sign_up"),
    path('tree_search_page/', views.tree_search_page, name="tree_search_page"),
    path('test/<str:my_query>/', views._test_page, name="test_page"),
    re_path(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    path('<path:notfound404>', views.home_page, name="home_page"),

] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/DataManagementSystem/updateapp/urls.py
from django.urls import path
from updateapp import views


app_name = 'updateapp'

urlpatterns = [
    path('', views.home_page, name="home_page"),
    path('test/', views.test_page, name="test_page"),
    path('progress/', views.update_view, name="update_view_page"),
    path('fdog/', views.after_update_page, name="update_fdog_page"),
    path('mysql/', views.mysql_script, name="mysql_run"),
    path('clear_cache/', views.del_cache, name="clear_cache"),

] 

src/DataManagementSystem/updateapp/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from updateapp.DataBaseGenerator import SuperUpdate
import _thread
from datetime import datetime
import os
import pathlib
from django.contrib.admin.views.decorators import staff_member_required

@staff_member_required
def home_page(request):
    """
    other page
    """
    if request.method == "POST": 
        if request.POST['add_new_files']:
            update_db_function()
            return HttpResponse("Updating script lunched!")
        if request.POST['clear_cache']:
            SuperUpdate.clear_cache()

    if  os.path.exists(SuperUpdate.UPDATE_FILES_DIR+'assembly_summary_refseq.txt'):
        last_update_date = datetime.fromtimestamp(
                        pathlib.Path(SuperUpdate.UPDATE_FILES_DIR+'assembly_summary_refseq.txt').stat().st_mtime)
    else:
        last_update_date = "an unknown date"
    return render(request, "updateapp/home_page.html", 
            {"last_update_date":last_update_date,
            "fdog_run":os.path.exists(SuperUpdate.UPDATE_FILES_DIR+'fdog_seed.csv')}
                    )


@staff_member_required
def after_update_page(request):
    """
    This is the page for fdog and cluster usage
    """
    if request.method == "POST":  # to lunch fdog
        SuperUpdate.fdog_luncher(request.POST['my_new_slurm_script'])
        print(request.POST['my_new_slurm_script'].replace('\r\n','\n'))        
        return HttpResponse("cluster is lunched! you can see the progress with \"squeue\" command.\nPS: Do not forget to add the files to the data base after the cluster finishes!")
    SLURM_SCRIPT = """
    #!/bin/bash
    #SBATCH --partition=all,pool,inteli7
    #SBATCH --account=praktikant
    #SBATCH --cpus-per-task=10
    #SBATCH --mem-per-cpu=3000mb
    #SBATCH --job-name="fdog_DB"
    #SBATCH --output=/dev/null
    #SBATCH --error=/dev/null
    #SBATCH --array=[my_lines]%4

    echo This is task $SLURM_ARRAY_TASK_ID

    SEED=$(awk "FNR==$SLURM_ARRAY_TASK_ID" [my_file])
    NAME=`echo $SEED |cut -d ',' -f 1`
    TAX=`echo $SEED |cut -d ',' -f 2`
    END=`echo $SEED |cut -d ',' -f 3`

    fdog.addTaxon -f /share/gluster/GeneSets/NCBI-Genomes/${NAME:4:3}/${NAME:7:3}/${NAME:10:3}/$NAME.$END/raw_dir/protein.faa -i $TAX -o /share/gluster/GeneSets/NCBI-Genomes/${NAME:4:3}/${NAME:7:3}/${NAME:10:3}/$NAME.$END/fdog -c --cpus 10 --replace -v $END
    """.replace("    ", "")
    return render(request, "updateapp/fdog_page.html", 
            {"slurm_script": SLURM_SCRIPT}
                    )


@staff_member_required
def test_page(request):
    if request.method == 'GET':
        print(request.GET, len(request.GET.dict()))
    return HttpResponse("This is a celary testing page please take a look at the terminal!")


@staff_member_required
def update_view(request):
    """
    Update page 
    A funtions that creates a global instance at the first run 
    uses multithreading to update the data base while showing the progress at teh frontend
    """
    if request.method == "POST":
        print("stop open request")
        my_global_instance._stop_me = True
    try:
        step_indicator = my_global_instance.updating_status
        html_print = my_global_instance.html_print
        if step_indicator >= 100 or my_global_instance._stop_me :  # Stop refresh
            print("End Updating")
            exec("del(globals()['my_global_instance'])")
            return HttpResponseRedirect(reverse("updateapp:update_fdog_page"))
        else:
            refresh_page = not my_global_instance._stop_me
        print("checkpointing:", "my_global_instance" in globals().keys(), my_global_instance._job_done)
        return render(request, "updateapp/update_page.html", {
                                                            "step_indicator": step_indicator, 
                                                            "refresh":refresh_page,
                                                            "updating_status": html_print})
    except NameError:
        # exec is used to avoid: "variable referenced before assignment" 
        print("124, Here:", request.GET, request.GET['ignore_this_taxa'], request.GET['do_only_this_taxa'])
        if len(request.GET.dict())>1:
            ignore_this_taxa = request.GET['ignore_this_taxa']
            do_only_this_taxa = request.GET['do_only_this_taxa']
            exec("global my_global_instance\nmy_global_instance = SuperUpdate(ignore_this_taxa, do_only_this_taxa)")
            #my_global_instance = SuperUpdate(ignore_this_taxa, do_only_this_taxa)
            print("check_me", "my_global_instance" in globals().keys())
            _thread.start_new_thread(my_global_instance._start_update, ())
        else:
            exec(
            """
                print('Initiation o the update thread')
                global my_global_instance
                my_global_instance = SuperUpdate()
                _thread.start_new_thread(my_global_instance._start_update, ())
            """.replace('  ', ''), globals())
        
        step_indicator = my_global_instance.updating_status
        refresh_page = not my_global_instance._stop_me
        return render(request, "updateapp/update_page.html", {
                                                            "step_indicator": step_indicator, 
                                                            "refresh":refresh_page,
                                                            "updating_status": my_global_instance.html_print})
    except Exception as e:
        print("Fatal error", e)
        return HttpResponse("Fatal Error while updating!")


def mysql_script(request):
    """
    this page updates the database with the new containt with through a mySQL command
    requires fdog file that will be deleted after use
    """
    SuperUpdate.mySQL_add_annotations_and_blast()
    return render(request, "updateapp/mysql_run.html")



def del_cache(request):
    for one_file in os.listdir(SuperUpdate.UPDATE_FILES_DIR):
        os.remove(os.path.join(SuperUpdate.UPDATE_FILES_DIR, one_file))
    return HttpResponseRedirect(reverse("updateapp:home_page"))

src/DataManagementSystem/templates/updateapp/fdog_page.html
<!DOCTYPE html>
{% extends "mainapp/base.html" %}
{% load static %}
{% load bootstrap5 %}
    {% block body_block%}
    <div class="jumbotron">
      <h2>Update ended:</h2>
      <hr>
      <ol>
        <li>fna files</li>
        <li>faa files</li>
        <li>gff files</li>
      </ol>
      <hr>
      <h3>Proceed to fdog update?</h3>
      <hr>
      <form action="" method="post">
        <div class="row">
          <textarea class="col-md-12 form-control" id="cola" name="my_new_slurm_script" style="height: 200px;">{{ slurm_script }}</textarea >
        </div>
        <hr>
        <div class="input-group mb-3">
          <span class="input-group-addon" id="basic-addon1">slurm output path: </span>
          <input class="form-control" type="text" value="" id="fna" name="slurm_output" placeholder="choose a path to find the cluster output" aria-describedby="basic-addon1">
        </div>
        <hr> 
        <p></p>
        <div>
          {% csrf_token %}
          <a class="btn btn-primary pull-left" href="/media/updateapp/fdog_seed.csv" download>
            download fdog seed
          </a>
          <a class="btn btn-primary pull-left" href="/media/updateapp/my_last_update.log" download>
            download update log
          </a>
          <a href="{% url 'home_page'%}" class="col-md-2 btn btn-danger pull-right" >Cancel<a>
          <input type="submit" class="col-md-2 btn btn-warning pull-right" value="Run on cluster" name="cluster_script"/>
        </div>
      </form>
    </div>

    {% endblock %}

src/DataManagementSystem/templates/updateapp/home_page.html
<!DOCTYPE html>
{% extends "mainapp/base.html" %}
    {% block body_block%}
    <div class="jumbotron">
      <h2>Hello Sir {{user.username}}!</h2>
      <a href={% url 'updateapp:clear_cache' %} class="btn btn-info pull-right">Delete Cache</a>
      <p style="text-align:center;"><h3>It's {% now "jS F Y H:i" %}</h3></p>
      <hr>
      <h3>Last update was made on {{ last_update_date }}</h3>
      <hr>
      <form class=""  action="progress/?ignore_this_taxa={{ignore_this_taxa}}?do_only_this_taxa={{do_only_this_taxa}}" enctype="multipart/form-data">
        <label class="custom-file-label" for="files_list">Start new update</label>
        {% if fdog_run %}
        <div class="alert alert-warning" role="alert">
          <strong>fdog seed file found!</strong>
          <hr>Please click on this button to update with the last data to the database!
          <a type="button" href={% url 'updateapp:mysql_run' %} class="btn btn-warning form-control" >Add the new cluster files to DB </a>
        </div>
        {% endif %}
        <div class="input-group mb-3">
          <span class="input-group-addon" id="basic-addon1">Ignore</span>
          <input class="form-control" type="text" value="Bacteria" id="fna" name="ignore_this_taxa" placeholder="You can choose to ignore taxonomy" aria-describedby="basic-addon1">
        </div>
        <p></p>
        <div class="input-group input-group">
          <span class="input-group-addon" id="basic-addon2">Targeted update</span>
          <input class="form-control sm-6" type="text" value="" id="fna" name="do_only_this_taxa" placeholder="You can choose to add only specific taxonomy" aria-describedby="basic-addon2">
        </div>
        <p></p>
        <button type="button" class="btn btn-danger form-control" data-toggle="modal" data-target="#doublecheck">Start update</button>
        <!-- Double check window -->
        <div class="modal fade" id="doublecheck" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h4 class="modal-title custom_align" id="Heading">Procceed with update?</h4>
              </div><!-- modal-header -->
              <div class="modal-body">
                Updating the database might take a while. Do you want to proceed?
                  <hr>

              </div>

              <div class="modal-footer ">
                <button type="submit" class="btn btn-warning">Yes</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
              </div>

            </div>  <!-- /.modal-content -->
          </div>  <!-- /.modal-dialog -->
        </div>
      </form>

    </div>   

    {% endblock %}

src/DataManagementSystem/templates/updateapp/progress_page.html
<!DOCTYPE html>
{% extends "mainapp/base.html" %}
{% load static %}
    {% block body_block%}
    <meta http-equiv="refresh" content="{{ stop }}" />
    <div class="jumbotron">
      <h3>Updating in progress:</h1>
      <hr>
      Updating Species table
      <div class="progress">
        <div class="progress-bar" role="progressbar" style="width: {{ step_indicator }}0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
      Updating Assembly table
      <div class="progress">
        <div class="progress-bar" role="progressbar" style="width: 100%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
      Updating Genomic Annotation table
      <div class="progress">
        <div class="progress-bar" role="progressbar" style="width: 100%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
      Updating Proteins tables
      <div class="progress">
        <div class="progress-bar" role="progressbar" style="width: 9%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
      Updating Feature Annotations table
      <div class="progress">
        <div class="progress-bar" role="progressbar" style="width: 0%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
      Updating BlastDB table
      <div class="progress">
        <div class="progress-bar" role="progressbar" style="width: 0%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
      Updating DiamondDB table
      <div class="progress">
        <div class="progress-bar" role="progressbar" style="width: 0%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
      <form action="" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-warning pull-right" name="stop_me" >Cancel</button>
        <input type="submit" class="btn btn-warning pull-right" value="Pause" name="stop_me"/>
      </form>
    </div>
    

    {% endblock %}

src/DataManagementSystem/templates/updateapp/test_page.html
<!DOCTYPE html>
{% extends "mainapp/base.html" %}
    {% block body_block%}
    <div class="jumbotron">
      <h2>Hello Sir {{user.username}}!</h2>
      <h3>It's {% now "jS F Y H:i" %}</h3>
      <h3>This is the update page:</h3>
      <hr>
      <form class=""  method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label class="custom-file-label" for="files_list">Choose a folder to update</label>
        <input type="file" class="custom-folder-input form-control" name="files_list" id="files_list" webkitdirectory directory multiple/>*
        <ul></ul>
        <button type="button" class="btn btn-danger form-control" data-toggle="modal" data-target="#doublecheck">Upload</button>
        <!-- Double check window -->
        <div class="modal fade" id="doublecheck" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h4 class="modal-title custom_align" id="Heading">Procceed?</h4>
              </div><!-- modal-header -->

              <div class="modal-body">
                Updating new files might take a while. Do you want to proceed?
                  <hr>

              </div>

              <div class="modal-footer ">
                <button type="submit" class="btn btn-warning">Yes</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
              </div>

            </div>  <!-- /.modal-content -->
          </div>  <!-- /.modal-dialog -->
        </div>
      </form>
    </hr>
      <h2>Manually input file: </h2>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          <label for="formGroupExampleInput">GCF</label>
          <input type="text" class="form-control" id="formGroupExampleInput" >
        </div>
        <div class="form-group">
          <label for="formGroupExampleInput1">NCBI ID</label>
          <input type="text" class="form-control" id="formGroupExampleInput1" >
        </div>
        <input type="file" name="my_file">
        <button class="btn btn-warning form-control" type="submit">Upload file</button>
      </form>
      {% if url %}
        <p>Uploaded file: <a href="{{ url }}">{{ url }}</a></p>
      {% endif %}
    </div>   

    {% endblock %}

src/DataManagementSystem/templates/updateapp/update_page.html
<!DOCTYPE html>
{% extends "mainapp/base.html" %}
{% load static %}
{% load bootstrap5 %}
    {% block body_block%}
    {% if refresh %}
      <meta http-equiv="refresh" content=30 />
    {% endif %}

    <div class="jumbotron">
      <h2>Updating in progress:</h2>
      <hr>
      <h4>Updating...</h4>
      {% if refresh %}
      in progress:
      <div class="progress progress-striped active">
          <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width: {{ step_indicator }}%" aria-valuenow="{{ step_indicator }}" aria-valuemin="0" aria-valuemax="100">{{ step_indicator }}%</div>
      </div>
      {% else %}
      Finished 
      <div class="progress">
          <div class="progress-bar progress-bar-success" role="progressbar" style="width: {{ step_indicator }}%" aria-valuenow="{{ step_indicator }}" aria-valuemin="0" aria-valuemax="100">Done!</div>
      </div>
      {% endif %}
      <h2>Status:</h2>
      <hr>
      <div class="row">
        <textarea class="col-md-12 form-control" style="height: 200px;">{{ updating_status }}</textarea >
      </div>
      <p></p>
      <div>
      <form action="" method="post">
        {% csrf_token %}
        <button type="submit" class="col-md-2 btn btn-danger pull-right" name="stop_me" >Cancel</button>
        &nbsp;
        <input type="submit" class="col-md-2 btn btn-warning pull-right" value="Pause" name="stop_me"/>
      </form>
    </div>
    </div>


    {% endblock %}