src/DataManagementSystem/Uni/urls.py
from django.contrib import admin
from django.views.generic.base import RedirectView
from django.urls import path, include, re_path
from mainapp import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('', views.user_login, name="login"),
    path('update/', include('updateapp.urls')),
    path('admin/', admin.site.urls),
    path('home_page/', views.home_page, name="home_page"),
    path('logout/', views.user_logout, name="logout"),
    path('my_space', views.my_space, name="my_space"),
    path('results_page/<str:my_query>/', views.results_page, name="results_page"),
    path('search_page/', views.search_page, name="search_page"),
    path('sign_up/', views.sign_up_page, name="sign_up"),
    path('tree_search_page/', views.tree_search_page, name="tree_search_page"),
    path('test/<str:my_query>/', views._test_page, name="test_page"),
    re_path(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    path('<path:notfound404>', views.home_page, name="home_page"),

] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/DataManagementSystem/updateapp/urls.py
from django.urls import path
from updateapp import views


app_name = 'updateapp'

urlpatterns = [
    path('', views.home_page, name="home_page"),
    path('test/', views.test_page, name="test_page"),
    path('progress/', views.update_view, name="update_view_page"),
    path('fdog/', views.after_update_page, name="update_fdog_page"),
    path('mysql/', views.mysql_script, name="mysql_run"),
    path('clear_cache/', views.del_cache, name="clear_cache"),

] 

src/DataManagementSystem/mainapp/forms.py
from django.forms import ModelForm, TextInput, URLField, ImageField, CharField,\
    PasswordInput
from mainapp.models import Species, Assembly, UserProfileInfo
from django.contrib.auth.models import User

# The form class.
class UserProfileInfoForm(ModelForm):
    class Meta():
        """docstring for Meta.  """
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')


class UserLoginForm(ModelForm):
    password = CharField(widget=PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'email', 'password',)



class SpeciesForm(ModelForm):
    """Species form"""
    class Meta:
        model = Species
        exclude = ['image_path']
        widgets = {
            'ncbi_id': TextInput(attrs={'type':'number','class': 'form-control'}),
            'species_name': TextInput(attrs={'class': 'form-control'}),
            'species_code': TextInput(attrs={'class': 'form-control'}),
            'alias': TextInput(attrs={'class': 'form-control'}),
            'category': TextInput(attrs={'class': 'form-control'}),
            'commun_name': TextInput(attrs={'class': 'form-control'}),
            'taxonomy': TextInput(attrs={'class': 'form-control'}),
        }

class AssemblyForm(ModelForm):
    """Assembly Form"""
    class Meta:
        model = Assembly
        exclude = ['dir_location','file_location']
        widgets = {
            'species': TextInput(attrs={'class': 'form-control'}),
            'assembly_id': TextInput(attrs={'type':'number','class': 'form-control'}),
            'assembly_version': TextInput(attrs={'type':'number','class': 'form-control'}),
            'assembly_source': TextInput(attrs={'class': 'form-control'}),
            'addditional_notes': TextInput(attrs={'class': 'form-control'}),
        }  # Check species again

src/DataManagementSystem/mainapp/views.py
from django.shortcuts import render
from mainapp.forms import UserLoginForm, UserProfileInfoForm
from django.http import HttpResponseRedirect, HttpResponse, HttpRequest
from django.core.paginator import Paginator
from django.urls import reverse
from django.contrib.auth.decorators import login_required
#from django.contrib.admin.views.decorators import staff_member_required
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth import authenticate, login, logout
from mainapp.brain import BigBrain
from mainapp.models import Searchresults, Searchregister

# Create your views here.
@login_required
def _test_page(request, my_query="nope", what_is_checked="0123456"):
    """test page to try things out"""
    if my_query:  # Check is a search querry is given
        print("NEWWWWWWWWWWWWWWWWWWWWWW ----------------------------------------------------------------------------")
        MySearch = BigBrain(request.user)
        MySearch.look_for_this(my_query, list(what_is_checked))
        results_paginator = Paginator(MySearch.search_results, 10)  # Shows 10 results per page
        #print("range paginator", results_paginator.num_pages, results_paginator.num_pages)
        page_number = int( request.GET.get('page') if request.GET.get('page') is not None else 1 )
        #print("Test paginator: ",   MySearch.html_paginator_bar_generator(page_number, results_paginator.num_pages))
        #print("My paginator results\n:", results_paginator.get_page(1))
        my_results_dict = {
                'search_querry':my_query, 
                "my_search_results": results_paginator.page(page_number), 
                "my_search_collumns": MySearch.column_maker(), 
                "my_search_path_results": MySearch.get_only_mysql_rslt_path(),
                "page_pagination_bar": MySearch.html_paginator_bar_generator(page_number, results_paginator.num_pages)
                }
        
        return render(request,"mainapp/test_page.html", my_results_dict)
    else:
        print("Empty search querry given...")
        
    return render(request, "mainapp/test_page.html", {"search_querry":my_query})


@login_required
def home_page(request, notfound404=None):
    """Main page after user is logged in"""
    return render(request, "mainapp/home_page.html")


@login_required
def my_space(request):
    """Reworked my_space after user is logged in"""
    print(request.POST)
    searchregister_object = Searchregister.objects.filter(user_id=request.user.id).order_by("-date_of_the_experiment")
    MY_SEARCH_COLLUMNS = ['Date', 'Query']
    MY_RESULTS_COLLUMNS = BigBrain(request.user).column_maker()
    if "search target" in dict(request.POST):
        print("wow", request.POST["search target"])
        search_target = request.POST["search target"]
        searchresults_object = Searchresults.objects.filter(search_id=search_target)
        paginator_searchresults = Paginator(searchresults_object, 10)
        page_number = int( request.GET.get('page') if request.GET.get('page') is not None else 1 )
    elif request.GET.get('target'):
        print(">>>>>>>>>>> worked!!!!!!!!!!!!!!!!!!!!", request.GET.get('target'))
        search_target = request.GET.get('target')
        print("oizer", request.GET)
        searchresults_object = Searchresults.objects.filter(search_id=search_target)
        paginator_searchresults = Paginator(searchresults_object, 10)
        page_number = int( request.GET.get('page') if request.GET.get('page') is not None else 1 )
    else:
        print("NO")
        search_target=""
        searchresults_object = []
        paginator_searchresults = Paginator(searchresults_object, 10)
        page_number = 1

    print("PAGEEEEEEEEEEEEEEEEEEEEEEEEEE : ", page_number)
    my_render_dict = {
            "my_searchs": searchregister_object,
            "my_search_collumns": MY_SEARCH_COLLUMNS,
            "my_results_object": paginator_searchresults.page(page_number),
            "my_results_collumns": MY_RESULTS_COLLUMNS,
            "page_pagination_bar": BigBrain(request.user).html_paginator_bar_generator(page_number, paginator_searchresults.num_pages),
            "object_target": search_target
            }

    return render(
            request,
            "mainapp/my_space_page.html",
            my_render_dict
            )


@login_required
def results_page(request,  my_query=""):
    """results page:
        accessible from search_page only
    """
    if len(my_query)<1:
        return HttpResponseRedirect(reverse('search_page'))
    searchresults_object = Searchresults.objects.filter(search_id=my_query)
    paginator_search_results = Paginator(searchresults_object, 10)
    page_number = int( request.GET.get('page') if request.GET.get('page') is not None else 1 )
    my_results_dict = {
            'search_querry': Searchregister.objects.filter(user_id=request.user.id, search_id=my_query).last().querry_used, 
            "my_search_results": paginator_search_results.page(page_number), 
            "my_search_collumns": BigBrain(request.user).column_maker(), 
            "my_search_path_results": [],
            "page_pagination_bar": BigBrain(request.user).html_paginator_bar_generator(page_number, paginator_search_results.num_pages)
            }
    return render(request,"mainapp/results_page.html", my_results_dict)


@login_required
def search_page(request):
    """search page:
        contains form
        the user can look for the wished files and add them to his personal Space (working)
    """
    print(request.user.id)
    if request.method == 'POST':
        my_request_dict = dict(request.POST)
        if "save_location" not in my_request_dict:
            my_search_querry = request.POST["search_querry"]
            if len(my_request_dict)>2:  # Check if something is checked
                if my_search_querry:  # Check is a search querry is given
                    MySearch = BigBrain(request.user)
                    MySearch.look_for_this(my_search_querry, my_request_dict["what_is_checked"])
                    # NEW
                    search_target = Searchregister.objects.filter(user_id=request.user.id, querry_used=my_search_querry).last()
                    return HttpResponseRedirect(reverse('results_page', args=(search_target,)))

    return render(request,"mainapp/search_page.html")


def sign_up_page(request):
    """
    sign up page
    """
    # Incase user is logged in
    if request.method == 'GET':
        if request.user.is_authenticated:  #Check if the user is already online
            return HttpResponseRedirect(reverse("home_page"))

    registered = False
    if request.method == 'POST':
        #print("youhou", request.POST)
        user_form = UserLoginForm(request.POST)
        profile_form = UserProfileInfoForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True

            # User auto login
            user_login = authenticate(
                    username=request.POST['username'],
                    password=request.POST['password']
                    )
            print(user_login)
            if user_login:
                if user_login.is_active:
                    login(request, user_login)
                    return HttpResponseRedirect(reverse("home_page"))

                else:
                    return HttpResponse("Account not active")
            else:
                print("someone tried to login and failed!")
                return HttpResponse("Invalid login details supplied")

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserLoginForm()
        profile_form = UserProfileInfoForm()
    return render(
        request,
        'mainapp/sign_up_page.html',
        {   'user_form': user_form,
            'profile_form': profile_form,
            'registered':registered
            }
    )


@login_required
def tree_search_page(request):
    """search page:
        contains form
        the user can look for the wished files
        and they will be automaatically added to his/her personal Space
    """
    pass  # To be programmed later

    return render(request,"mainapp/tree_search_page.html")


def user_login(request):
    if request.user.is_authenticated:  #Check if the user is already online
        return HttpResponseRedirect(reverse("home_page"))

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse("home_page"))

            else:
                return HttpResponse("Account not active")
        else:
            print("someone tried to login and failed!")
            return HttpResponse("Invalid login details supplied")
    else:
        return render(request, 'mainapp/login_page.html', {})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('login'))

src/DataManagementSystem/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<!-- CSS only -->
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>DDB : DataBase Browser</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" media="all" type="text/css" href="/static/css/mini_bootstrap.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="text/javascript" href="/javascript/jquery.js"></script>
    <script type="text/javascript" href="/javascript/mini_bootstrap.js"></script>
    <!-- Need to have JQuery and Javascript for DropDown Actions to work -->
    <script
    src="http://code.jquery.com/jquery-3.1.1.js"
    integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
    crossorigin="anonymous"></script>  <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>
  <body>
    <!-- Navigation bar-->
    <nav class="navbar navbar-default navbar-inverse navbar-static-top">
      <div class="container-fluid">

        <a href="{% url 'home_page'%}" class="navbar-brand"><strong>DBB</strong></a>
        <!--Small-->
        <button type="button"
                class="collapsed navbar-toggle"
                data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1"
                aria-expanded="false"
                aria-controls="bs-example-navbar-collapse-1"
                aria-label="Toggle navigation"
                >
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- Not Small-->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'search_page'%}">Search</a></li>

            <li>
              <a class="dropdown-menu-dark dropdown-toggle dropdown-toggle-split" role="button" data-toggle="dropdown" aria-expanded="false"><span class="caret"></span>
              </a> <!-- dropdown-->
              <div class="dropdown-menu text-light bg-dark" > <!-- dropdown-menu-dark -->
                <a class="dropdown-item form-control text-light bg-dark" href="{% url 'tree_search_page'%}">Tree Search</a>
              </div>
            </li>

            <li><a href="{% url 'my_space'%}">My Space</a></li>
            {% if user.is_superuser %}
            <li><a href="{% url 'updateapp:home_page' %}">Update</a></li>
            {% endif %}
            <li><a href="#">About</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li><a href="">{{user.username}}</a></li>
            <li>
              <button type="button" class="btn btn-default navbar-btn"><a href="{% url 'logout'%}">Logout</a></button>
            </li>
            {% else %}
            <li><a href="{% url 'sign_up'%}">Sign up</a></li>
            <li>
              <button type="button" class="btn btn-default navbar-btn"><a href="{% url 'login'%}">Login</a></button>
            </li>
            {% endif %}
          </ul>
        </div>  <!-- /.collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class="container-fluid">

    {% block body_block %}
    {# Anything outside of this will be inherited.#}
    {% endblock %}
    </div>

  </body>
</html>

src/DataManagementSystem/templates/mainapp/home_page.html
<!DOCTYPE html>
{% extends "mainapp/base.html" %}
    {% block body_block%}
    <div class="jumbotron">
      <h1>Hello {{user.username}} and welcome to the DDB Application!</h1>
      <h3>This is the home page. Please use the navigation bar!</h1>
    </div>


    {% endblock %}

src/DataManagementSystem/templates/mainapp/login_page.html
<!DOCTYPE html>
{% extends "mainapp/base.html" %}
  {% block body_block%}
		<!--https://bootsnipp.com/snippets/z1Bpy -->
    	<div class="row ">
			<div class=" jumbotron col-md-6 col-md-offset-3">
					<h2> Log in </h1>
						<hr>
						<div class="row">
							<div class="col-lg-12">
								<form action="{% url 'login' %}" method="POST" role="form">
                  {% csrf_token %}
									<div class="form-group">
										<input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Username" value="">
									</div>
									<div class="form-group">
										<input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password">
									</div>
									<div class="form-group text-center">
										<input type="checkbox" tabindex="3" class="" name="remember" id="remember">
										<label for="remember"> Remember Me</label>
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-sm-6 col-sm-offset-3">
												<input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login  btn-primary" value="Log In">
											</div>
										</div>
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-lg-6">
												<div class="text-center">
													<a href="{% url 'home_page'%}" tabindex="5" class="forgot-password">Forgot Password?</a>
												</div>
											</div>
                      <div class="col-lg-6">
												<div class="text-center">
													<a href="{% url 'sign_up'%}" tabindex="5" class="forgot-password">No account?</a>
												</div>
											</div>
										</div>
									</div>
							</div>
						</div>
				</div>
			</div>
		</div>
{% endblock %}

src/DataManagementSystem/templates/mainapp/login_page_reworked.html
<!DOCTYPE html>
{% extends "mainapp/base.html" %}
  {% block body_block%}
		<!--https://bootsnipp.com/snippets/z1Bpy -->
    	<div class="row ">
			<div class=" jumbotron col-md-6 col-md-offset-3">
				<div class="panel panel-login">
					<div class="panel-heading">
						<div class="row">
							<div class="col-xs-6">
								<a href="#" class="active" id="login-form-link">Login</a>
							</div>
							<div class="col-xs-6">
								<a href="{% url 'sign_up'%}" id="register-form-link">Register</a>
							</div>
						</div>
						<hr>
					</div>
					<div class="panel-body">
						<div class="row">
							<div class="col-lg-12">
								<form id="login-form" action="" method="post" role="form" style="display: block;">
									<div class="form-group">
										<input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Username" value="">
									</div>
									<div class="form-group">
										<input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password">
									</div>
									<div class="form-group text-center">
										<input type="checkbox" tabindex="3" class="" name="remember" id="remember">
										<label for="remember"> Remember Me</label>
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-sm-6 col-sm-offset-3">
												<input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login" value="Log In">
											</div>
										</div>
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-lg-12">
												<div class="text-center">
													<a href="" tabindex="5" class="forgot-password">Forgot Password?</a>
												</div>
											</div>
										</div>
									</div>
								</form>
								<form id="register-form" action="" method="post" role="form" style="display: none;">
									<div class="form-group">
										<input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Username" value="">
									</div>
									<div class="form-group">
										<input type="email" name="email" id="email" tabindex="1" class="form-control" placeholder="Email Address" value="">
									</div>
									<div class="form-group">
										<input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password">
									</div>
									<div class="form-group">
										<input type="password" name="confirm-password" id="confirm-password" tabindex="2" class="form-control" placeholder="Confirm Password">
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-sm-6 col-sm-offset-3">
												<input type="submit" name="register-submit" id="register-submit" tabindex="4" class="btn btn-primary form-control " value="Register Now">
											</div>
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
{% endblock %}

src/DataManagementSystem/templates/mainapp/my_space_page.html
<!DOCTYPE html>
<!DOCTYPE html>
{% extends "mainapp/base.html" %}
  {% block body_block%}
  <script type="text/javascript" src="/static/javascript/my_space_page.js"> </script>
  <div class=" jumbotron">
  <div class="row">
  <div class="col-md-3 table-wrapper-scroll-y my-custom-scrollbar table-hover">
    <h2> My searches: </h2>
    <hr>
    <div class="row">
      <div class="col-4">
        <hr>
        <div class="table-responsive table-striped">
          <form class="" method="POST">
            {% csrf_token %}
            <table id="mytable" class="table table-bordred table-striped table-hover table-sm">
              <thead class="thead-dark">
                <!-- table collum names -->
                 <th><input class="form-check-input allChecked form-control " type="checkbox" value="all_checked" id="checkall" name="all_checked" /></th>
                 {% for cl in my_search_collumns %}
                   <th class="th-sm">{{ cl }}</th>
                 {% endfor %}
                 <th class="text-center" style="width:10%">View</th>
                 <th class="text-center" style="width:5%">Delete</th>
               </thead>
              <tbody>
                {% for object in my_searchs %}
                  <tr>
                  <td><input type="checkbox" class="form-check-input form-control checkthis" value={{object.search_id}} name="what_is_checked"/></td>
                  <td>{{object.date_of_the_experiment}}</td>
                  <td>{{object.querry_used}}</td>
                  <td> <a href="?target={{object.search_id}}"> <span class="glyphicon glyphicon-search  form-control" aria-hidden="true"></span> </a></td>
                  <td><p data-placement="top" data-toggle="tooltip" title="Delete"><button class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#deletewindow" ><span class="glyphicon glyphicon-trash"></span></button></p></td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </form>
        </div> <!-- table reponsive -->
      </div>
    </div>
  </div> <!-- End First table block-->
  <div class="vr"></div>
  <div class="col-md-9"><!-- Start second table block-->
     <div class="row">
        <div class="col-md-12">
          <h3>Search results</h3>
          <hr>
          <div class="table-responsive">
            <table id="mytable" class="table table-bordred table-striped table-hover">
              <thead>
                 <th><input type="checkbox" id="checkall" /></th>
                 {% for cl in my_results_collumns %}
                   <th>{{ cl }}</th>
                 {% endfor %}
                 <th>Remove</th>
               </thead>
               <tbody>
                 {% for object in my_results_object %}
                   <tr>
                   <td><input type="checkbox" class="form-check-input form-control checkthis" value={{object.search_id}} name="what_is_checked"/></td>
                   <td>{{object.file_type}}</td>
                   <td>{{object.assembly_id}}</td>
                   <td>{{object.assembly_version}}</td>
                   <td>{{object.ncbi_id}}</td>
                   <td>{{object.species_name}}</td>
                   <td>{{object.alias}}</td>
                   <td>{{object.assembly_source}}</td>
                   <td>{{object.file_location}}</td>
                   <td><p data-placement="top" data-toggle="tooltip" title="Delete"><button class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#deletewindow" ><span class="glyphicon glyphicon-trash"></span></button></p></td>
                   </tr>
                 {% endfor %}
               </tbody>
            </table>
          </div> <!-- table reponsive -->
        </div> <!-- col-md-12 -->
     </div> <!-- row -->
    <hr>
    <div class="container">
      <ul class="pagination pull-right">
        {% if my_results_object.has_previous %}
          <li><a href="?target={{object_target}}&page=1"><span class="glyphicon glyphicon-step-backward"></span>First</a></li>
          <li><a href="?target={{object_target}}&page={{ my_results_object.previous_page_number }}"><span class="glyphicon glyphicon-chevron-left"></span></a></li>
        {% endif %}
        {% for page_num in page_pagination_bar %}
          {% if page_num == my_results_object.number %}
            <li class="active"><a href="?target={{object_target}}"> {{my_results_object.number}}</a></li> 
          {% else %}
            <li><a href="?target={{object_target}}&page={{page_num}}">{{page_num}}</a></li>
          {% endif %}
        {% endfor %}
        {% if my_results_object.has_next %}
          <li><a href="?target={{object_target}}&page={{ my_results_object.next_page_number }}"><span class="glyphicon glyphicon-chevron-right"></span></a></li>
          <li><a href="?target={{object_target}}&page={{ my_results_object.paginator.num_pages }}"> Last <span class="glyphicon glyphicon-step-forward"></span></a></li>
        {% endif %}
      </ul>
      Page {{ my_results_object.number }} of {{ my_results_object.paginator.num_pages }}
      <br>
      <br>
      <hr>
    </div>

    <div class="container">
      <h2>Filter</h2>
      <button type="button" class="btn btn-primary btn-lg pull-right" data-title="Save shortcuts" data-toggle="modal" data-target="#downloadwindow">Download</button>
      <button type="button" class="btn btn-secondary btn-lg pull-right" disabled>Discard</button>
      <button type="button" class="btn btn-success btn-lg " disabled>Kmer</button>
      <button type="button" class="btn btn-warning btn-lg " disabled>Busco</button>
    </div>

  </div> <!-- second table block -->
    </div><!-- class="row"-->
    <!-- Download button -->
    <div class="modal fade" id="downloadwindow" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
    <form class="" method="POST">
      {% csrf_token %}
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
        <h4 class="modal-title custom_align" id="Heading">Save location</h4>
      </div><!-- modal-header -->
      <div class="modal-body">
          <div class="alert alert-info">  <h4> <span> </span> <span class="glyphicon glyphicon-download-alt"></span>These are the links to your desired files: </h4> <br>
            <div >
              {% for object in my_results_object %}
                <p>{{object.file_location}}</p>
              {% endfor %}
            </div>
          </div>
          <hr>
      </div>
      <div class="modal-footer ">
        <button onclick=copyThis()  class="btn btn-warning">Copy</button>
        <button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span>Close</button>
      </div>
    </form>
    </div>  <!-- /.modal-content -->
  </div>  <!-- /.modal-dialog -->
  </div>
  </div> <!-- jambootron -->
<div id="text_to_copy" hidden data-dismiss="modal">{% for object in my_results_object %}{{object.file_location}}
{% endfor %}</div>
  {% endblock %}

src/DataManagementSystem/templates/mainapp/sign_up_page.html
<!DOCTYPE html>
{% extends "mainapp/base.html" %}
{% block body_block%}
	<div class=" col-md-2 col-sm-0 col-xs-0">

	</div>
	<div class="jumbotron col-md-8 col-sm-12 col-xs-12 center-block">
    {% if registered %}
      <h1> Thank you for registering! :D</h1>
    {% else %}
      <h2> Registration form </h1>
				<hr>
      <form action="{% url 'sign_up' %}"  method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        <input type="submit" class="btn btn-primary form-control" value="Sign up">
      </form>
    {% endif %}
  </div>
{% endblock %}